name: Task Issue
description: 作業進捗用issue
body:
  - type: textarea
    id: why
    attributes:
      label: 詳細説明
      description: 起きている事象、達成したい目的について記入してください
    validations:
      required: false
  - type: textarea
    id: ac
    attributes:
      label: クローズ条件
    validations:
      required: false
      value: |
        1.
        2.
        3.
      render: bash
  - type: checkboxes
    id: genre
    attributes:
      label: 作業ジャンル
      options:
        - 調査
        - ドキュメント
        - ミーティング
        - コーディング
        - デザイン
        - その他
  - type: textarea
    id: appendix
    attributes:
      label: 補足情報
      description: 参考URLなどあれば
